### ISSUE TITLE
Cabocha tried to decode text with the encoding 'euc-jp' but it failed

### ISSUE THREAD

**Issue by PengtaoNi** [timmahrt/pyJuliusAlign#10]
Hi, I ran into a pyjuliusalign.jProcessingSnippet.TextDecodingError:
Cabocha tried to decode text with the encoding 'euc-jp' but it failed. If you specify a different encoding in alignFromTextgrid.convertCorpusToKanaAndRomaji() that will probably fix the problem.
I'm working on a mac and I tried changing charset to euc-jp in the cabocharc file but it doesn't work either. Is there somewhere else I should configure? Thank you!

**Comment by timmahrt** [comment]
Did you try changing the coding argument in convertCorpusToKanaAndRomaji to utf-8?

Off the top of my head, I don't have a good idea.  If I recall correctly, the encoding is determined at install time.  How did you install cabocha?  

Are you running this over your own data?  Or is this the example files?
`https://github.com/timmahrt/pyJuliusAlign/blob/main/examples/align_example.py`

I might be able to take a look at it tonight.

**Comment by PengtaoNi** [comment]
Thank you for your response!
I installed cabocha with homebrew and ran the example files. I'm not sure how to access convertCorpusToKanaAndRomaji.

**Comment by timmahrt** [comment]
You should be able to do everything from within the example file `align_example.py`

Try changing line 39
https://github.com/timmahrt/pyJuliusAlign/blob/main/examples/align_example.py#L39

from:
cabochaEncoding = "euc-jp" 
to
cabochaEncoding = "utf-8"

convertCorpusToKanaAndRomaji is called on line 49
https://github.com/timmahrt/pyJuliusAlign/blob/main/examples/align_example.py#L49

**Comment by PengtaoNi** [comment]
I changed line 39 and it worked! Thanks again
