### ISSUE TITLE
sh: /segmentation-kit-4.3.1/bin/julius-4.3.1.exe: cannot execute binary file

### ISSUE THREAD

**Issue by PengtaoNi** [timmahrt/pyJuliusAlign#11]
Sorry but I ran into another problem with segmentation kit on mac as title. Is it because it only supports windows?

**Comment by timmahrt** [comment]
The examples are for windows, however, I'm able to use the examples on my mac after configuring the example files.

You'll need to configure the scripts to use the appropriate parameters (in this case line 28 https://github.com/timmahrt/pyJuliusAlign/blob/main/examples/align_example.py#L28).  On mac, that is probably just 'julius'.  The full path might be needed if julius is not in your path.

**Comment by PengtaoNi** [comment]
Do you mean I should change https://github.com/timmahrt/pyJuliusAlign/blob/main/examples/align_example.py#L32 juliusScriptPath to julius? I did that and it still didn't work:
pyjuliusalign.juliusAlignment.JuliusScriptExecutionFailed: \ Execution Failed.  Please check the following:
- Perl and the julius4.pl script exist in the locations specified
- you have edited the 'user configuration' part of 'segment_julius4.pl'
- script arguments are correct

Here is the command that python attempted to run:
/usr/local/bin/perl /Users/nipengtao/Desktop/julius-master/julius/julius /Users/nipengtao/Desktop/pyJuliusAlign-main/examples/files/align_tmp

**Comment by timmahrt** [comment]
The script will only work if it can find all of the various tools it is using (julius, perl, etc).

Can you run this from the command line?
`/Users/nipengtao/Desktop/julius-master/julius/julius`

If that runs ok (ie you don't get the error 'julius command not found' etc), then align_example.py should work fine.  If not, you need to find the correct path to julius (maybe just `/Users/nipengtao/Desktop/julius-master/julius`)?

**Comment by PengtaoNi** [comment]
/Users/nipengtao/Desktop/julius-master/julius/julius does run on command line, but with the following error:
Unrecognized character \xCF; marked by <-- HERE after <-- HERE near column 1 at /Users/nipengtao/Desktop/julius-master/julius/julius line 1.

**Comment by timmahrt** [comment]
It's hard for me to diagnose from here.  Can you confirm that all of the necessary software exists?

In align_example.py the following are set (to something that your os can find from the terminal)
```
juliusScriptPath = "/Users/tmahrt/Downloads/segmentation-kit/segment_julius.pl"
soxPath = "sox"
cabochaPath = "cabocha"
perlPath = "perl"
```

And you modified segment_julius.pl?

What line did align_example.py crash at?

**Comment by PengtaoNi** [comment]
Thank you so much for your patience but I'm confused. Should the juliusScriptPath be the path to julius or to segment_julius.pl? If it's segment_julius.pl, where should I put the path to julius?

**Comment by timmahrt** [comment]
Sorry, I wasn't clear.

juliusScriptPath should be the full path to the file `segment_julius.pl`

You will need to modify `segment_julius.pl` so that it points to the full path of julius on your computer (for me it is line 52:
`$juliusbin="/Users/tmahrt/Downloads/julius-4.5/julius/julius";`

and like 56
`$hmmdefs="/Users/tmahrt/Downloads/segmentation-kit/models/hmmdefs_monof_mix16_gid.binhmm"; # monophone model`

**Comment by PengtaoNi** [comment]
It worked! Thank you so much for your help!

**Comment by timmahrt** [comment]
I'm glad it worked out!

**Comment by timmahrt** [comment]
I'll close this now but if you have any further questions, feel free to open this issue or a new one! Thank you!
