### ISSUE TITLE
Mecab/Cabocha returns wrong result for 一週間

### ISSUE THREAD

**Issue by timmahrt** [timmahrt/pyJuliusAlign#6]
This issue was reported by itsupera on gitter

This is not a problem with pyJuliusAlign but is a problem that affects pyJuliusAlign users

For example
一週間 -> いち＋しゅうー＞いっしゅう
(There is probably a name for this process)

These sorts of rules don't get respected by mecab/cabocha leading to pronunciation/alignment errors.

**Comment by itsupera** [comment]
So in the end, the issue was that I was using unidic instead of ipadic.

Since ipadic works better at segmenting into phonemes, you can probably close this issue.
