### ISSUE TITLE
Document installation of ipadic for MeCab/CaboCha

### ISSUE THREAD

**Issue by itsupera** [timmahrt/pyJuliusAlign#7]
ipadic is the dictionary to use for segmenting into phonemes, but this is not the one configured by default when installing MeCab.

It would be useful to document this such as new users don't get confused ( as I used to be :) )

**Comment by timmahrt** [comment]
I want to sit down and try out the different dictionaries.  I wonder if I had the same problem last time I used this library but wasn't aware of it.

**Comment by timmahrt** [comment]
Related:
https://github.com/timmahrt/pyJuliusAlign/issues/6
https://github.com/timmahrt/pyJuliusAlign/issues/5

**Comment by timmahrt** [comment]
I added a caution to the readme file and directed users to this issue.  I think for now we can close it.  Feel free to reopen it if you'd like!
