### ISSUE TITLE
segment_julius.pl script arguments incorrect?

### ISSUE THREAD

**Issue by codexq123** [timmahrt/pyJuliusAlign#8]
Hi,

It's really useful for me. I am using python 3.8 and found it not a big problem for python3. But I have trouble in the final step.
when i run the command "cmdList = [perlPath, juliusScriptPath, resourcePath]", it raised error as follow:

pyjuliusalign.juliusAlignment.JuliusScriptExecutionFailed: \ Execution Failed.  Please check the following:
- Perl and the julius4.pl script exist in the locations specified
- you have edited the 'user configuration' part of 'segment_julius4.pl'
- script arguments are correct

I am very sure my location is OK, because they are absolute paths rather than relative paths. And my perlPath is  r"C:\cygwin64\bin\perl.exe". I wonder there is something wrong with segment_julius.pl.

**Comment by timmahrt** [comment]
Hi,
I'm sorry that you're having this problem. I am on a mac so it might be difficult for me to help, if this is a Windows-specific problem.

Did you configure segment_julius4.pl as specified in the requirements section?
https://github.com/timmahrt/pyJuliusAlign#requirements

You need to add lines and set the absolute path for hmmdefs.  For line 33 you might need to use `$datadir = ".\wav";` instead of `$datadir = "./wav";`

**Comment by codexq123** [comment]
Hi,

Thanks for your advice. I was working on windows system. I try to run the segment_julius.pl separately as below. I send no parameter to the command line which means I will use the sample provided by segmentation-kit in the './wav' folder.  

It told me: the system cannot find the path specified. Also the output file './wav/sample.log' is empty. BTW, I used absolute path on line 33 rather than '.\wav'. That fixed the bug on line 33.

![image](https://user-images.githubusercontent.com/28684231/122347169-55f5d280-cf7c-11eb-82b2-4a001e58a009.png)

**Comment by timmahrt** [comment]
Windows uses '\\' while Mac uses '/'.  Did you try:
`C:\FinanceData\prototype\pyJulius\segmentation-kit\wav`?

**Comment by codexq123** [comment]
Thanks a lot. Problem solved!

For Windows system:
1. Most paths in the segment_julius.pl should be changed to absolute paths.
2. Line 136 in segment_julius.pl should be changed to '$command = "echo $f.wav | julius-4.3.1.exe -h $hmmdefs -dfa $f.dfa -v $f.dict";'. You should set up environment variable for julius-4.3.1.exe too.

**Comment by timmahrt** [comment]
I'm glad to hear that it worked out.  I'll update the README file with your comments.  Thanks!

**Comment by codexq123** [comment]
I will summarize all the adapt for Windows10 python 3.8 later. Thanks a lot.

**Comment by timmahrt** [comment]
Thank you!

**Comment by timmahrt** [comment]
I'll close this issue now. If you have any more questions, please feel free to reopen this issue or open a new one!
